---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "caddy.fullname" . }}
  labels:
    app.kubernetes.io/component: loadbalancer
    {{- include "caddy.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    {{- include "caddy.selectorLabels" . | nindent 4 }}


{{- if .Values.elasticsearch.use_incluster_service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      protocol: TCP
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
{{- end }}


{{- if .Values.mongodb.use_incluster_service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
{{- end }}


{{ if .Values.redis.use_incluster_service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
{{ end }}


{{ if .Values.mysql.use_incluster_service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
{{ end }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3310
      protocol: TCP
  selector:
    {{- include "clamav.selectorLabels" . | nindent 4 }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "forum.fullname" . }}
  labels:
      {{- include "forum.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 4567
      protocol: TCP
  selector:
    {{- include "forum.selectorLabels" . | nindent 4 }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mfe.fullname" . }}
  labels:
      {{- include "mfe.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8002
      protocol: TCP
  selector:
    {{- include "mfe.selectorLabels" . | nindent 4 }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cms.fullname" . }}
  labels:
    {{- include "cms.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
  selector:
    {{- include "cms.selectorLabels" . | nindent 4 }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lms.fullname" . }}
  labels:
    {{- include "lms.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
  selector:
    {{- include "lms.selectorLabels" . | nindent 4 }}
